In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Decimal Scaling

In [51]:
df = pd.read_csv('processed_penguins.csv')

In [52]:
df.body_mass_g = df.body_mass_g/10000
df.bill_length_mm = df.bill_length_mm/100
df.bill_depth_mm = df.bill_depth_mm/100
df.flipper_length_mm = df.flipper_length_mm/1000

In [53]:
df.head()

study_name species     island clutch_completion    date_egg  bill_length_mm  \
0    PAL0708  Adelie  Torgersen               Yes  2007-11-11           0.395   
1    PAL0708  Adelie  Torgersen               Yes  2007-11-16           0.403   
2    PAL0708  Adelie  Torgersen               Yes  2007-11-16           0.367   
3    PAL0708  Adelie  Torgersen               Yes  2007-11-16           0.393   
4    PAL0708  Adelie  Torgersen                No  2007-11-15           0.389   

   bill_depth_mm  flipper_length_mm  body_mass_g     sex  delta_15  delta_13  \
0          0.174              0.186       0.3800  FEMALE   8.94956 -24.69454   
1          0.180              0.195       0.3250  FEMALE   8.36821 -25.33302   
2          0.193              0.193       0.3450  FEMALE   8.76651 -25.32426   
3          0.206              0.190       0.3650    MALE   8.66496 -25.29805   
4          0.178              0.181       0.3625  FEMALE   9.18718 -25.21799   

   study_day  
0          2  
1          7  
2          7  
3          7  
4          6

## Min-Max Normalization

In [54]:
df2 = pd.read_csv('processed_penguins.csv')

In [55]:
def minmax_scaler(x):
    xmin = np.min(x)
    xmax = np.max(x)
    output = (x-xmin)/(xmax-xmin)
    return output

In [56]:
df2.body_mass_g = minmax_scaler(df2.body_mass_g)
df2.bill_length_mm = minmax_scaler(df2.bill_length_mm)
df2.bill_depth_mm = minmax_scaler(df2.bill_depth_mm)
df2.flipper_length_mm = minmax_scaler(df2.flipper_length_mm)

In [65]:
df2.head()

study_name species     island clutch_completion    date_egg  bill_length_mm  \
0    PAL0708  Adelie  Torgersen               Yes  2007-11-11        0.269091   
1    PAL0708  Adelie  Torgersen               Yes  2007-11-16        0.298182   
2    PAL0708  Adelie  Torgersen               Yes  2007-11-16        0.167273   
3    PAL0708  Adelie  Torgersen               Yes  2007-11-16        0.261818   
4    PAL0708  Adelie  Torgersen                No  2007-11-15        0.247273   

   bill_depth_mm  flipper_length_mm  body_mass_g     sex  delta_15  delta_13  \
0       0.511905           0.237288     0.305556  FEMALE   8.94956 -24.69454   
1       0.583333           0.389831     0.152778  FEMALE   8.36821 -25.33302   
2       0.738095           0.355932     0.208333  FEMALE   8.76651 -25.32426   
3       0.892857           0.305085     0.263889    MALE   8.66496 -25.29805   
4       0.559524           0.152542     0.256944  FEMALE   9.18718 -25.21799   

   study_day  
0          2  
1          7  
2          7  
3          7  
4          6

In [27]:
df2.body_mass_g.min()

0.0

In [28]:
(3800-2700)/(6300-2700)

0.3055555555555556

In [61]:
df3 = pd.read_csv("processed_penguins.csv")

In [62]:
def std_scaler(x):
    mean = np.mean(x)
    std = np.std(x)
    output = (x-mean)/std
    return output

In [63]:
df3.body_mass_g = std_scaler(df3.body_mass_g)
df3.bill_length_mm = std_scaler(df3.bill_length_mm)
df3.bill_depth_mm = std_scaler(df3.bill_depth_mm)
df3.flipper_length_mm = std_scaler(df3.flipper_length_mm)

In [64]:
df3.head()

study_name species     island clutch_completion    date_egg  bill_length_mm  \
0    PAL0708  Adelie  Torgersen               Yes  2007-11-11       -0.832100   
1    PAL0708  Adelie  Torgersen               Yes  2007-11-16       -0.685906   
2    PAL0708  Adelie  Torgersen               Yes  2007-11-16       -1.343780   
3    PAL0708  Adelie  Torgersen               Yes  2007-11-16       -0.868649   
4    PAL0708  Adelie  Torgersen                No  2007-11-15       -0.941746   

   bill_depth_mm  flipper_length_mm  body_mass_g     sex  delta_15  delta_13  \
0       0.138739          -1.091764    -0.512317  FEMALE   8.94956 -24.69454   
1       0.444184          -0.446007    -1.192986  FEMALE   8.36821 -25.33302   
2       1.105981          -0.589508    -0.945470  FEMALE   8.76651 -25.32426   
3       1.767779          -0.804761    -0.697954    MALE   8.66496 -25.29805   
4       0.342369          -1.450518    -0.728893  FEMALE   9.18718 -25.21799   

   study_day  
0          2  
1          7  
2          7  
3          7  
4          6

In [66]:
df4 = pd.read_csv("processed_penguins.csv")

In [67]:
import sklearn.preprocessing as pp

In [68]:
body_mass = np.array(df4.body_mass_g).reshape(-1,1)

In [70]:
#body_mass

In [74]:
X = np.array(df4[['bill_length_mm','bill_depth_mm','flipper_length_mm','body_mass_g']])

In [75]:
X

array([[  39.5,   17.4,  186. , 3800. ],
       [  40.3,   18. ,  195. , 3250. ],
       [  36.7,   19.3,  193. , 3450. ],
       ...,
       [  50.4,   15.7,  222. , 5750. ],
       [  45.2,   14.8,  212. , 5200. ],
       [  49.9,   16.1,  213. , 5400. ]])

In [76]:
scaler = pp.StandardScaler().fit(X)

In [77]:
scaled = scaler.transform(X)

In [88]:
scaler.std_

AttributeError: 'StandardScaler' object has no attribute 'std_'

In [79]:
new_df = pd.DataFrame(scaled)

In [80]:
new_df

0         1         2         3
0   -0.832100  0.138739 -1.091764 -0.512317
1   -0.685906  0.444184 -0.446007 -1.192986
2   -1.343780  1.105981 -0.589508 -0.945470
3   -0.868649  1.767779 -0.804761 -0.697954
4   -0.941746  0.342369 -1.450518 -0.728893
..        ...       ...       ...       ...
319  0.575020 -1.744839  0.917259  0.879962
320  0.501922 -1.439394  0.989010  0.787144
321  1.159797 -0.726689  1.491265  1.900967
322  0.209534 -1.184856  0.773757  1.220297
323  1.068425 -0.523059  0.845508  1.467814

[324 rows x 4 columns]

In [81]:
min_max_scaler = pp.MinMaxScaler()

In [82]:
min_max_scaled = min_max_scaler.fit_transform(X)

In [83]:
min_max_scaler.scale_

array([0.03636364, 0.11904762, 0.01694915, 0.00027778])

In [89]:
min_max_scaled

array([[0.26909091, 0.51190476, 0.23728814, 0.30555556],
       [0.29818182, 0.58333333, 0.38983051, 0.15277778],
       [0.16727273, 0.73809524, 0.3559322 , 0.20833333],
       ...,
       [0.66545455, 0.30952381, 0.84745763, 0.84722222],
       [0.47636364, 0.20238095, 0.6779661 , 0.69444444],
       [0.64727273, 0.35714286, 0.69491525, 0.75      ]])